//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classics_2014 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color graphNormal {
            get {
                return ((global::System.Drawing.Color)(this["graphNormal"]));
            }
            set {
                this["graphNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color graphWindOut {
            get {
                return ((global::System.Drawing.Color)(this["graphWindOut"]));
            }
            set {
                this["graphWindOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color graphDirectionOut {
            get {
                return ((global::System.Drawing.Color)(this["graphDirectionOut"]));
            }
            set {
                this["graphDirectionOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color graphBothOut {
            get {
                return ((global::System.Drawing.Color)(this["graphBothOut"]));
            }
            set {
                this["graphBothOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string mySqlDataBaseServerIP {
            get {
                return ((string)(this["mySqlDataBaseServerIP"]));
            }
            set {
                this["mySqlDataBaseServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("main")]
        public string mySqlDataBaseName {
            get {
                return ((string)(this["mySqlDataBaseName"]));
            }
            set {
                this["mySqlDataBaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string mySqlDataBaseUser {
            get {
                return ((string)(this["mySqlDataBaseUser"]));
            }
            set {
                this["mySqlDataBaseUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mySqlDataBasePassword {
            get {
                return ((string)(this["mySqlDataBasePassword"]));
            }
            set {
                this["mySqlDataBasePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string directoryMasterFile {
            get {
                return ((string)(this["directoryMasterFile"]));
            }
            set {
                this["directoryMasterFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool userIsAdvanced {
            get {
                return ((bool)(this["userIsAdvanced"]));
            }
            set {
                this["userIsAdvanced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string userLockPassword {
            get {
                return ((string)(this["userLockPassword"]));
            }
            set {
                this["userLockPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int flopsToMaintainColourDirection {
            get {
                return ((int)(this["flopsToMaintainColourDirection"]));
            }
            set {
                this["flopsToMaintainColourDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int flopsToMaintainColourSpeed {
            get {
                return ((int)(this["flopsToMaintainColourSpeed"]));
            }
            set {
                this["flopsToMaintainColourSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int compHaltLength {
            get {
                return ((int)(this["compHaltLength"]));
            }
            set {
                this["compHaltLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color sideTextStandarColour {
            get {
                return ((global::System.Drawing.Color)(this["sideTextStandarColour"]));
            }
            set {
                this["sideTextStandarColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color sideTextWindOutColour {
            get {
                return ((global::System.Drawing.Color)(this["sideTextWindOutColour"]));
            }
            set {
                this["sideTextWindOutColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color sideTextDirectionOutColour {
            get {
                return ((global::System.Drawing.Color)(this["sideTextDirectionOutColour"]));
            }
            set {
                this["sideTextDirectionOutColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioAlarmsEnabled {
            get {
                return ((bool)(this["AudioAlarmsEnabled"]));
            }
            set {
                this["AudioAlarmsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public float DangerWindSpeed {
            get {
                return ((float)(this["DangerWindSpeed"]));
            }
            set {
                this["DangerWindSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int DangerDirectionChange {
            get {
                return ((int)(this["DangerDirectionChange"]));
            }
            set {
                this["DangerDirectionChange"] = value;
            }
        }
    }
}
