//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classics_2014.Accuracy {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class AccuracySpecificSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AccuracySpecificSettings defaultInstance = ((AccuracySpecificSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AccuracySpecificSettings())));
        
        public static AccuracySpecificSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
